package com.androidxx.cart.orm;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SHOPPING_CARD".
 */
public class ShoppingCard {

    private Long id;
    private String productName;
    private Float productPrice;
    private Integer productNum;
    private Long productId;

    public ShoppingCard() {
    }

    public ShoppingCard(Long id) {
        this.id = id;
    }

    public ShoppingCard(Long id, String productName, Float productPrice, Integer productNum, Long productId) {
        this.id = id;
        this.productName = productName;
        this.productPrice = productPrice;
        this.productNum = productNum;
        this.productId = productId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public Float getProductPrice() {
        return productPrice;
    }

    public void setProductPrice(Float productPrice) {
        this.productPrice = productPrice;
    }

    public Integer getProductNum() {
        return productNum;
    }

    public void setProductNum(Integer productNum) {
        this.productNum = productNum;
    }

    public Long getProductId() {
        return productId;
    }

    public void setProductId(Long productId) {
        this.productId = productId;
    }

}
